use super::*;

pub(super) fn goose_runtime() -> &'static KnownAcpRuntime {
    &KnownAcpRuntime {
        id: "goose",
        label: "Goose",
        display_label: "Goose",
        sort_priority: 1,
        onboarding_visible: false,
        commands: &["goose"],
        aliases: &[],
        default_args: &["acp"],
        default_parallelism: None,
        defer_agent_start_until_work: true,
        default_idle_timeout_secs: None,
        icon_url: "",
        icon_scale: 1.0,
        avatar_url: "",
        superseded_avatar_urls: &[],
        mcp_command: None,
        mcp_hooks: false,
        underlying_cli: None,
        cli_install_commands: &[],
        cli_install_commands_windows: &[],
        adapter_install_commands: &[],
        cli_install_instructions_url: "",
        adapter_install_instructions_url: "",
        cli_install_hint: "",
        adapter_install_hint: "",
        skill_dir: None,
        supports_acp_model_switching: false,
        accepts_harness_model: true,
        model_env_var: Some("GOOSE_MODEL"),
        provider_env_var: Some("GOOSE_PROVIDER"),
        provider_locked: false,
        default_env: &[],
        enforced_env: &[],
        scrub_env_vars: &[],
        config_file_path: Some("~/.config/goose/config.yaml"),
        config_file_format: Some("yaml"),
        supports_acp_native_config: true,
        thinking_env_var: Some("GOOSE_THINKING_EFFORT"),
        max_tokens_env_var: Some("GOOSE_MAX_TOKENS"),
        context_limit_env_var: Some("GOOSE_CONTEXT_LIMIT"),
        required_normalized_fields: &["model", "provider"],
        login_hint: None,
        auth_probe_args: None,
        auth_login_args: None,
    }
}
