use super::KnownAcpRuntime;

pub(super) const GOOSE_AVATAR_URL: &str = "https://goose-docs.ai/img/logo_dark.png";
pub(super) const CLAUDE_CODE_AVATAR_URL: &str = "https://anthropic.gallerycdn.vsassets.io/extensions/anthropic/claude-code/2.1.77/1773707456892/Microsoft.VisualStudio.Services.Icons.Default";
pub(super) const CODEX_AVATAR_URL: &str = "https://openai.gallerycdn.vsassets.io/extensions/openai/chatgpt/26.5313.41514/1773706730621/Microsoft.VisualStudio.Services.Icons.Default";
pub(super) const LEGACY_DEVIN_AVATAR_URL: &str = "https://mintcdn.com/cognitionai/Hhrl_8XUBqA4VQ6v/logo/favicon.svg?fit=max&auto=format&n=Hhrl_8XUBqA4VQ6v&q=85&s=ab641f30c01bf5374b90b62209db569e";
// The official Devin mark is transparent. Keep the profile avatar self-contained
// and add a white canvas so the black mark remains visible in dark themes.
pub(super) const DEVIN_AVATAR_URL: &str = concat!(
    "data:image/svg+xml,%3Csvg%20width%3D%22425%22%20height%3D%22425%22%20viewBox%3D%220%200%20425%20425%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E",
    "%3Crect%20width%3D%22425%22%20height%3D%22425%22%20fill%3D%22white%22%2F%3E",
    "%3Cpath%20d%3D%22M70%20159.333V91.3471C70%2088.3592%2071.594%2085.5983%2074.1816%2084.1044L133.043%2050.1205C135.631%2048.6265%20138.819%2048.6265%20141.407%2050.1205L200.269%2084.1044C202.856%2085.5983%20204.45%2088.3592%20204.45%2091.3471V126.068C204.708%20137.606%20210.806%20148.734%20221.531%20154.926C232.256%20161.117%20244.942%20160.834%20255.063%20155.289L285.132%20137.929C287.719%20136.435%20290.907%20136.435%20293.495%20137.929L352.357%20171.913C354.944%20173.406%20356.538%20176.167%20356.538%20179.155V247.123C356.538%20250.111%20354.944%20252.872%20352.357%20254.366L293.495%20288.35C290.907%20289.844%20287.719%20289.844%20285.132%20288.35L255.306%20271.13C245.146%20265.456%20232.344%20265.117%20221.534%20271.358C210.809%20277.55%20204.711%20288.678%20204.453%20300.215V334.926C204.453%20337.914%20202.859%20340.675%20200.271%20342.169L141.41%20376.153C138.822%20377.647%20135.634%20377.647%20133.046%20376.153L74.1845%20342.169C71.5969%20340.675%2070.0028%20337.914%2070.0028%20334.926V266.959C70.0029%20263.971%2071.5969%20261.21%2074.1845%20259.716L133.046%20225.732C135.634%20224.238%20138.822%20224.238%20141.41%20225.732L171.547%20243.132C181.656%20248.638%20194.306%20248.906%20205.005%20242.729C215.815%20236.488%20221.922%20225.231%20222.088%20213.595C221.83%20202.057%20215.732%20189.737%20205.008%20183.545C194.283%20177.353%20181.597%20177.636%20171.476%20183.181L141.269%20200.72C138.67%20202.229%20135.461%20202.228%20132.864%20200.716L74.1576%20166.562C71.5835%20165.065%2070%20162.311%2070%20159.333Z%22%20fill%3D%22black%22%2F%3E",
    "%3C%2Fsvg%3E"
);
pub(super) const BUZZ_AGENT_AVATAR_URL: &str =
    "https://raw.githubusercontent.com/block/buzz/refs/heads/main/crates/buzz-agent/buzz-agent.png";

pub(super) const KNOWN_ACP_RUNTIMES: &[KnownAcpRuntime] = &[
    KnownAcpRuntime {
        id: "goose",
        label: "Goose",
        display_label: "Goose",
        sort_priority: 10,
        onboarding_visible: false,
        commands: &["goose"],
        aliases: &[],
        default_args: &["acp"],
        default_parallelism: None,
        defer_agent_start_until_work: true,
        default_idle_timeout_secs: None,
        icon_url: "/runtime-icons/goose.svg",
        icon_scale: 1.25,
        avatar_url: GOOSE_AVATAR_URL,
        superseded_avatar_urls: &[],
        mcp_command: None,
        mcp_hooks: false,
        underlying_cli: Some("goose"),
        cli_install_commands: &["curl -fsSL https://github.com/aaif-goose/goose/releases/download/stable/download_cli.sh | CONFIGURE=false bash"],
        // Goose's stable release currently publishes only the Unix installer;
        // its official Windows instructions intentionally point at this main-branch script.
        cli_install_commands_windows: &["powershell.exe -NoProfile -ExecutionPolicy Bypass -Command \"$env:CONFIGURE='false'; irm https://raw.githubusercontent.com/aaif-goose/goose/main/download_cli.ps1 | iex\""],
        adapter_install_commands: &[],
        cli_install_instructions_url: "https://goose-docs.ai/docs/getting-started/installation/",
        adapter_install_instructions_url: "",
        cli_install_hint: "Buzz requires the Goose CLI; the desktop app alone is not enough.",
        adapter_install_hint: "",
        skill_dir: Some(".goose/skills"),
        supports_acp_model_switching: false,
        accepts_harness_model: true,
        model_env_var: Some("GOOSE_MODEL"),
        provider_env_var: Some("GOOSE_PROVIDER"),
        provider_locked: false,
        default_env: &[("GOOSE_MODE", "auto")],
        enforced_env: &[],
        scrub_env_vars: &[],
        config_file_path: Some("~/.config/goose/config.yaml"),
        config_file_format: Some("yaml"),
        supports_acp_native_config: true,
        thinking_env_var: Some("GOOSE_THINKING_EFFORT"),
        max_tokens_env_var: Some("GOOSE_MAX_TOKENS"),
        context_limit_env_var: Some("GOOSE_CONTEXT_LIMIT"),
        required_normalized_fields: &["model", "provider"],
        login_hint: None,
        auth_probe_args: None,
        auth_login_args: None,
    },
    KnownAcpRuntime {
        id: "claude",
        label: "Claude Code",
        display_label: "Claude Code",
        sort_priority: 30,
        onboarding_visible: true,
        commands: &["claude-agent-acp", "claude-code-acp"],
        aliases: &["claude-code", "claudecode"],
        default_args: &[],
        default_parallelism: None,
        defer_agent_start_until_work: true,
        default_idle_timeout_secs: None,
        icon_url: "/runtime-icons/claude.png",
        icon_scale: 1.1,
        avatar_url: CLAUDE_CODE_AVATAR_URL,
        superseded_avatar_urls: &[],
        mcp_command: None,
        mcp_hooks: false,
        underlying_cli: Some("claude"),
        cli_install_commands: &["curl -fsSL https://claude.ai/install.sh | bash"],
        cli_install_commands_windows: &["powershell.exe -NoProfile -ExecutionPolicy Bypass -Command \"irm https://claude.ai/install.ps1 | iex\""],
        adapter_install_commands: &["npm install -g @agentclientprotocol/claude-agent-acp"],
        cli_install_instructions_url: "https://code.claude.com/docs/en/getting-started",
        adapter_install_instructions_url: "https://github.com/agentclientprotocol/claude-agent-acp",
        cli_install_hint: "Buzz requires the Claude Code CLI; the desktop app alone is not enough.",
        adapter_install_hint: "Install the Claude Code ACP adapter via npm.",
        skill_dir: Some(".claude/skills"),
        supports_acp_model_switching: false,
        accepts_harness_model: true,
        model_env_var: None,
        provider_env_var: None,
        provider_locked: true,
        default_env: &[],
        enforced_env: &[],
        scrub_env_vars: &[],
        config_file_path: Some("~/.claude/settings.json"),
        config_file_format: Some("json"),
        supports_acp_native_config: false,
        thinking_env_var: None,
        max_tokens_env_var: None,
        context_limit_env_var: None,
        required_normalized_fields: &[],
        login_hint: Some("Run the Claude CLI to complete authentication."),
        auth_probe_args: Some(&["claude", "auth", "status"]),
        auth_login_args: None,
    },
    KnownAcpRuntime {
        id: "codex",
        label: "Codex",
        display_label: "Codex",
        sort_priority: 40,
        onboarding_visible: true,
        commands: &["codex-acp"],
        aliases: &[],
        default_args: &[],
        default_parallelism: None,
        defer_agent_start_until_work: true,
        default_idle_timeout_secs: None,
        icon_url: "/runtime-icons/codex.png",
        icon_scale: 1.1,
        avatar_url: CODEX_AVATAR_URL,
        superseded_avatar_urls: &[],
        mcp_command: Some("buzz-dev-mcp"),
        mcp_hooks: false,
        underlying_cli: Some("codex"),
        cli_install_commands: &["curl -fsSL https://chatgpt.com/codex/install.sh | sh"],
        cli_install_commands_windows: &["powershell.exe -NoProfile -ExecutionPolicy Bypass -Command \"irm https://chatgpt.com/codex/install.ps1 | iex\""],
        adapter_install_commands: &["npm install -g @agentclientprotocol/codex-acp"],
        cli_install_instructions_url: "https://developers.openai.com/codex/cli/",
        adapter_install_instructions_url: "https://github.com/agentclientprotocol/codex-acp",
        cli_install_hint: "Buzz requires the Codex CLI; the desktop app alone is not enough.",
        adapter_install_hint: "Install the Codex ACP adapter via npm.",
        skill_dir: Some(".codex/skills"),
        supports_acp_model_switching: false,
        accepts_harness_model: true,
        model_env_var: None,
        provider_env_var: None,
        provider_locked: false,
        default_env: &[],
        enforced_env: &[],
        scrub_env_vars: &[],
        config_file_path: Some("~/.codex/config.toml"),
        config_file_format: Some("toml"),
        supports_acp_native_config: false,
        thinking_env_var: None,
        max_tokens_env_var: None,
        context_limit_env_var: None,
        required_normalized_fields: &[],
        login_hint: Some("Run `codex login` to authenticate."),
        // Verified: `codex login status` exits 0 when logged in, non-zero otherwise.
        auth_probe_args: Some(&["codex", "login", "status"]),
        auth_login_args: None,
    },
    KnownAcpRuntime {
        id: "devin",
        label: "Devin",
        display_label: "Devin",
        sort_priority: 20,
        onboarding_visible: true,
        commands: &["devin"],
        aliases: &[],
        default_args: &["acp"],
        // One official CLI session is the safe local default. Explicit request
        // or persona values still win.
        default_parallelism: Some(1),
        // The official CLI performs meaningful startup work before its first
        // prompt. Pay that cost when the managed runtime starts so the first
        // user message does not also become a process-health probe.
        defer_agent_start_until_work: false,
        // Devin normally emits ACP progress well inside this window. A fully
        // silent native server is replaced and the queued batch retried rather
        // than appearing to hang under the generic 15-minute tool allowance.
        default_idle_timeout_secs: Some(120),
        icon_url: "/runtime-icons/devin.svg",
        icon_scale: 1.1,
        avatar_url: DEVIN_AVATAR_URL,
        superseded_avatar_urls: &[LEGACY_DEVIN_AVATAR_URL],
        mcp_command: None,
        mcp_hooks: false,
        underlying_cli: Some("devin"),
        cli_install_commands: &["curl -fsSL https://cli.devin.ai/install.sh | bash"],
        cli_install_commands_windows: &[
            "powershell.exe -NoProfile -Command \"irm https://static.devin.ai/cli/setup.ps1 | iex\"",
        ],
        adapter_install_commands: &[],
        cli_install_instructions_url: "https://docs.devin.ai/cli",
        adapter_install_instructions_url: "",
        cli_install_hint: "Buzz requires the Devin CLI; the desktop app alone is not enough.",
        adapter_install_hint: "",
        skill_dir: Some(".devin/skills"),
        supports_acp_model_switching: false,
        // Devin's native ACP server owns model choice. Passing Buzz's global
        // model would imply a capability we do not expose and causes the
        // official CLI to reject unrelated Buzz model IDs before falling back.
        accepts_harness_model: false,
        model_env_var: None,
        provider_env_var: None,
        provider_locked: false,
        default_env: &[],
        // Buzz's harness historically defaults to bypassing ACP permission
        // requests. The native Devin runtime must always retain the official
        // CLI's safe permission behavior.
        enforced_env: &[
            ("BUZZ_ACP_PERMISSION_MODE", "default"),
            ("BUZZ_ACP_AUTO_APPROVE_PERMISSIONS", "false"),
            ("BUZZ_ACP_INTERACTIVE_PERMISSIONS", "true"),
            ("BUZZ_ACP_SELF_PUBLISH_COMPLETION_GRACE", "30"),
        ],
        // The official CLI gives this legacy ambient key precedence over the
        // account established by `devin auth login`. Remove it without reading
        // its value so readiness and usage attribution share one identity.
        scrub_env_vars: &["WINDSURF_API_KEY"],
        config_file_path: None,
        config_file_format: None,
        supports_acp_native_config: false,
        thinking_env_var: None,
        max_tokens_env_var: None,
        context_limit_env_var: None,
        required_normalized_fields: &[],
        login_hint: Some("Run `devin auth login` to authenticate."),
        // Verified locally: the command exits 0 for an authenticated CLI.
        auth_probe_args: Some(&["devin", "auth", "status"]),
        auth_login_args: Some(&["devin", "auth", "login"]),
    },
    KnownAcpRuntime {
        id: "buzz-agent",
        label: "Buzz Agent",
        display_label: "Buzz",
        sort_priority: 0,
        onboarding_visible: false,
        commands: &["buzz-agent"],
        aliases: &[],
        default_args: &[],
        default_parallelism: None,
        defer_agent_start_until_work: true,
        default_idle_timeout_secs: None,
        icon_url: "/app-icon@2x.png",
        icon_scale: 1.1,
        avatar_url: BUZZ_AGENT_AVATAR_URL,
        superseded_avatar_urls: &[],
        mcp_command: Some("buzz-dev-mcp"),
        mcp_hooks: true,
        underlying_cli: None,
        cli_install_commands: &[],
        cli_install_commands_windows: &[],
        adapter_install_commands: &[],
        cli_install_instructions_url: "https://github.com/block/buzz",
        adapter_install_instructions_url: "https://github.com/block/buzz",
        cli_install_hint: "Ships with the Buzz desktop app.",
        adapter_install_hint: "",
        skill_dir: None,
        supports_acp_model_switching: true,
        accepts_harness_model: true,
        model_env_var: Some("BUZZ_AGENT_MODEL"),
        provider_env_var: Some("BUZZ_AGENT_PROVIDER"),
        provider_locked: false,
        default_env: &[],
        enforced_env: &[],
        scrub_env_vars: &[],
        config_file_path: None,
        config_file_format: None,
        supports_acp_native_config: false,
        thinking_env_var: Some("BUZZ_AGENT_THINKING_EFFORT"),
        max_tokens_env_var: Some("BUZZ_AGENT_MAX_OUTPUT_TOKENS"),
        context_limit_env_var: Some("BUZZ_AGENT_MAX_CONTEXT_TOKENS"),
        required_normalized_fields: &["model", "provider"],
        login_hint: None,
        auth_probe_args: None,
        auth_login_args: None,
    },
];
